### ISSUE TITLE
Process for altering workflow configuration

### ISSUE THREAD

**Issue by bzurkowski** [github/branch-deploy#147]
### Describe the Issue

I am trying to develop a process for altering the workflow configuration when using the branch-deploy action.

By design, the workflow is executed based on the configuration in the main branch, meaning I can only test changes after a merge. This poses a risk of introducing workflow bugs into the main branch.

Changing the workflow trigger, e.g., to `on: pull_request`, is not an option as the action is driven by issue comments.

What is the recommended development process when using this action?

Thank you in advance for any help. I am really enjoying working with this tool! 😃

**Comment by GrantBirki** [comment]
👋 Hi @bzurkowski sorry for taking so long to you on this. At this point you have probably already figured out your own workflow for making changes but I'll go ahead and share how I do this for others that might be looking for an answer as well.

It should be noted that my answer is the same for how we (at GitHub) and I (in personal projects) make changes to workflows in production repos.

First off, let's look at your comment here:

> By design, the workflow is executed based on the configuration in the main branch, meaning I can only test changes after a merge. This poses a risk of introducing workflow bugs into the `main` branch.

You are absolutely correct and this does indeed pose a level of risk. We can't "branch-deploy" our changes to the `github/branch-deploy` Action because of this design. It is actually a trade-off because we can't safely test changes before they land on the `main` branch for this Action's configurations... but the upside to this is that changes to this Action *can't be made until they are on the `main` branch*. Because of this, we can be confident that commenting `.deploy` will only run from the `main` branch and we can be assured that those changes have been reviewed and tested before they landed there.

Let's continue on and get to my explanation of how I upgrade versions of this Action in a production repository:

> What is the recommended development process when using this action?

It's not great but here is how it goes:

1. A new version of the `github/branch-deploy` Action is released. Let's use `v10.0.0` as an example here.
2. Either myself, or dependabot will open a pull request to update the `github/branch-deploy` Action to this latest version in repo XYZ
3. I or a teammate approves the changes, comments `.deploy` to meet the branch protection settings, and then we merge the pull request
4. Now the changes are on `main` and will be applied throughout the repo and on all other PRs that are open.

This absolutely does incur some risk as `v10.0.0` could have a bug and now you need another PRs to update to `v10.0.1` when it comes out, or rollback to a previous version.

The good news, is that I and GitHub are both very aware of this upgrade process so we do our absolute best to ensure this doesn't happen. Here is what we do to help ensure releases are smooth and you can reliably upgrade to them:

- This project has 100% test coverage
- Large or questionable changes are tagged as pre-releases and we test them internally in our project before rolling them out to the public via the "latest" release tag
- We test changes in sandbox repos to rule out bugs early and often
- We monitor this repo for any bug reports and squash them as quick as we can

---

Hopefully that helps! Feel free to re-open this issue if you have any further questions but I will go ahead and close it out for now. Thanks! 😄
