### ISSUE TITLE
Large plans/applies throw an odd error

### ISSUE THREAD

**Issue by ianwinsemius** [github/branch-deploy#173]
### Describe the Issue

When I try to do large deploys I get a failure like the one below:

```bash
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/****. Argument list too long
```

Feel free to slack me 😄

**Comment by GrantBirki** [comment]
@ianwinsemius I have good news and bad news for you. The good news is that this error isn't actually related to the `branch-deploy` Action at all. The bad news, is that it is related to the way GitHub Actions runners work and we will need to implement a fix in the repo where you found this issue.

I actually found this bug a long time ago when working on another Actions project and [documented it](https://github.com/GrantBirki/git-diff-action#known-issues)

> GitHub Actions can only support argument lists from environment variables up to a certain size

I don't know off the top of my head _what that size is_. All that I know is that when strings get too long and are being passed around as env vars in Actions, things break. The work around that I used in the `git-diff-action` was to pass things around by reading and writing to files instead. Yeah, its a hack and kinda a gross one but it works and resolved the issue at hand.

I'll take a look in "the repo where this is happening" and see if I can implement a fix.

---

I'll close this out as this issue is not related to the `branch-deploy` Action but rather GitHub Actions in general.
