### ISSUE TITLE
Removing non-sticky lock when retrying a failed job in multi-job workflows fails

### ISSUE THREAD

**Issue by bkonicek-calm** [github/branch-deploy#218]
### Describe the Issue

In a workflow configured to use this action in a multi-job configuration, if the deployment workflow originally fails and is re-tried using "Re-run jobs > Re-run failed jobs", the "Remove a non-sticky lock" step of the "result" job will always error out with

```
Run gh api \
  gh api \
    --method DELETE \
    'repos/{owner}/{repo}/git/refs/heads/staging-branch-deploy-lock'
  shell: /usr/bin/bash -e {0}
  env:
    GH_REPO: bkonicek-calm/branch-deploy-test
    GH_TOKEN: ***
  
gh: Reference does not exist (HTTP 4[2](https://github.com/bkonicek-calm/branch-deploy-test/actions/runs/6591572276/job/17910470241#step:5:2)2)
{"message":"Reference does not exist","documentation_url":"https://docs.github.com/rest/git/refs#delete-a-reference"}
Error: Process completed with exit code 1.
```

We could always trigger a new deployment, but in more complicated workflows that can cost a lot of time. It would be nice if we could just retry the failing jobs when possible (e.g. a missing config value caused the original failure)

### Action Configuration

https://github.com/bkonicek-calm/branch-deploy-test/blob/main/.github/workflows/pr_deployment.yml

### Relevant Actions Log Output

https://pipelinesghubeus9.actions.githubusercontent.com/Xmv5KJtKvOGHIycin2JVVwumt6WTcDqR22VW4O22M8m91PSios/_apis/pipelines/1/runs/6/signedlogcontent/6?urlExpires=2023-10-20T18%3A59%3A50.1307385Z&urlSigningMethod=HMACV1&urlSignature=ROHcFGJTsdlyr%2BM8v27rZYuI5ZsoRN%2FZVyT2w0dNPsY%3D

### Extra Information

Multiple job documentation: https://github.com/github/branch-deploy/blob/main/docs/examples.md#multiple-jobs

Example of a retried action: https://github.com/bkonicek-calm/branch-deploy-test/actions/runs/6591572276/attempts/2
- The first attempt, the "test" job failed, and the "result" job correctly succeeded and commented in the [PR](https://github.com/bkonicek-calm/branch-deploy-test/pull/1)
- The 2nd attempt after retrying the failed jobs, it failed on the "remove a non-sticky lock" step.

**Comment by GrantBirki** [comment]
:wave: @bkonicek-calm

I took a look at your workflow logs and the configuration around them. The "multiple step workflows" where `skip_completing` is set is what I would consider an "_advanced_" workflow setup. We don't offer too much support around these workflow types as they are custom and have a lot of variability by their very nature. That being said, I use them personally in a few projects where they are needed and they can be quite powerful.

I took a look at what was going on and realized that the way we treat locks in our example docs isn't up-to-date. Specifically [these lines here](https://github.com/github/branch-deploy/blob/ad977ccc24ae3f34843fa5a51a5ba8f28f9e80ff/docs/examples.md?plain=1#L815-L840) (that link now takes you to the updated version that will handle "sticky-locks" correctly :wink:)

I would suggest taking a look at the updated [Multiple Jobs](https://github.com/github/branch-deploy/blob/main/docs/examples.md#multiple-jobs) example docs since I just merged a PR related to it. I would also suggest using the latest version of the `github/branch-deploy` Action which is version `v8.1.0` at this time.

I tested out retrying workflows using the "Multiple Jobs" step in my own personal project ([here](https://github.com/GrantBirki/blog/blob/main/.github/workflows/branch-deploy.yml)) and was not able to replicate the issue.

**Comment by bkonicek-calm** [comment]
Thanks for taking a look @GrantBirki !

I've updated my workflow with the updated documentation (and updated my action to `v8.1.0`) but I'm now getting 
```
gh: No commit found for the ref staging-branch-deploy-lock (HTTP 404)
base64: invalid input
``` on the retry. I think this is happening because the lock branch was already deleted in attempt #1, even though it does still successfully create an empty `lock.json` file the error causes the step to fail immediately. 

I think a workaround could just be adding ` || true` to the end of the command like 
```
gh api \
  --method GET \
  'repos/{owner}/{repo}/contents/lock.json?ref=staging-branch-deploy-lock' \
  --jq '.content' \
  | base64 --decode \
  > lock.json || true
```

**Comment by bkonicek-calm** [comment]
Looks like that does work, but then it errors in the `else` clause because it's trying to delete a branch that no longer exists. Probably needs some other conditional logic to figure out if the branch is even there. 

Would it make more sense to instead skip the "remove a non-sticky lock" step altogether if the previous job failed? Then I think when it DOES succeed on a retry it should be able to work just fine without adding a bunch of other logic to the script.

**Comment by bkonicek-calm** [comment]
That didn't seem to make a difference unfortunately - although I do wonder how it was working on the first attempt of any workflow run without it!

Still getting 

```
gh: No commit found for the ref staging-branch-deploy-lock (HTTP 404)
base64: invalid input
Error: Process completed with exit code 1.
```

I believe that since on the first attempt when the job before "result" fails, it's deleting the lock branch, then when you re-run the failing jobs, it's not creating the branch again (since the `trigger` job didn't fail), so "result" can't lookup that branch to fetch `lock.json`. This is why re-running ALL jobs (not just failed) does work.

This was what I was suggesting about making the "Remove a non-sticky lock" conditional on the previous job succeeding. like

```
- name: Remove a non-sticky lock
  ${{ steps.deploy-status.outputs.DEPLOY_STATUS != 'failure' }}
  env:
    GH_REPO: ${{ github.repository }}
    GH_TOKEN: ${{ github.token }}
  run: |
    # Fetch the lock.json file from the branch
 ...

- name: remove eyes reaction
  continue-on-error: true
  env:
    GH_REPO: ${{ github.repository }}
    GH_TOKEN: ${{ github.token }}
  run: |
    gh api \
      --method DELETE \
      'repos/{owner}/{repo}/issues/comments/${{ needs.deploy-info.outputs.comment-id }}/reactions/${{ needs.deploy-info.outputs.initial-reaction-id }}'
```

^^ This worked, but then it errors on removing the eyes reaction since it was already removed in the previous attempt and changed to a failure reaction so I had to add `continue-on-error: true` to that step.

This probably isn't a totally foolproof solution but it might be good enough to avoid requiring people from re-running an entire workflow from the beginning every time there's a failure.
