### ISSUE TITLE
Explain intended usage of storing secrets in environment and making them available to deployment workflow

### ISSUE THREAD

**Issue by DocMoebiuz** [github/branch-deploy#283]
### Details

Ok, I tried to put the main question in the title. The docs are a little bit confusing about this.

Current situation: I have three github environments defined, and every environment holds the respective secrets and env-variables. Lets say they are called "dev,test,prod". Every environment holds a secret, e.g. MY_SECRET.

I have now set up the branch-deploy action so that I can deploy to these three environments.

Deployment is associated correctly, but the subsequent workflow steps won't be able to access "MY_SECRET".

Is that correct?

You are mentioning, that we should use an additional environment, e.g. dev-secrets, test-secrets and prod-secrets which serve as the environments that now provide the secrets for us through the standard property "environment" on job level.

I haven't tried that yet, but I would assume that:
* I have to dynamically determine the value in my workflow so that deployment environment and secrets environment are the corresponding ones, or is this solved by `branch-deploy`?
* I would end up with two actual deployments in my list (e.g. on the repo home page) for every deloyment that I trigger through `branch-deploy`

Please help me confirm my understanding.

**Comment by GrantBirki** [comment]
@DocMoebiuz First of all, thank you for writing all this up! It is really great to have this all in writing in a place that is searchable and for others to find in the future. You did a great job doing a deep-dive into how this Action works and how GitHub environments are wired up.

The two possible workarounds are both valid and cover the vast majority of use cases for folks using this Action to facilitate their deployments.  You did a great job explaining both the concept of using `secret-environments` and plain-old `repository secrets`.

For most folks, the ultimate deciding factor on "which one to use" for storing secrets often boils down to their risk tolerance. With environment secrets, you can actually them down to which `branch` can access them. Since all `issue_comment: types: [created]` workflow events are fired from the default branch (most often `main` / `master`), this means that you can lock secrets down really well when using this Action. For example, a bad actor would not be able to alter the workflow to `on: pull_request` and exfiltrate the secrets since the environment protection rules only allow them to be sourced from workflow that are related to the branch which you designated.

In contrast, if you used plain-old repository secrets, this is now of concern as you don't have the ability to lock them down with the same type of protection rules.

Here is an example of locking down environment secrets with a branch protection rule (from a repo using github/branch-deploy):

![Image](https://github.com/user-attachments/assets/0e3b8b02-c817-435b-bda1-23e7ffb46cc2)

That being said, using `environment-secrets` isn't the cleanest look and can be confusing to contributors when they see a little green rocket and _deployed to production-secrets_ on the homepage of a repo:

![Image](https://github.com/user-attachments/assets/d664664a-119c-471d-b6b8-0450f2b1b776)

Some orgs might have great security controls in-place and have the risk tolerance to just use repo secrets and that's fine too. It all comes down to what works best for you, and how you want to protection your secrets at the end of the day 😃

---

P.S. thank you for linking https://github.com/actions/runner/issues/2120! I'm going to poke around internally at GitHub and try to figure out more about this request. I personally think it would be great if we could use an environment just for the secrets it store and not for a full on deployment in a workflow.

Thanks!
