### ISSUE TITLE
Add an option to only wait for specific CI checks

### ISSUE THREAD

**Issue by tiagonbotelho** [github/branch-deploy#66]
Hi @GrantBirki 👋 I've currently encountered a scenario where we have a few CI tasks running in our PRs that shouldn't really block our deploys from going forward.

I've noticed by reading the docs that there doesn't seem to be a way of allow-listing only a number of CI checks or even just flat-out not waiting for CI to have finished run before we can go ahead with deploys.

I wonder if that is something there'd be appetite in adding to branch-deploy? 😊 

Massive thanks for working on this!

**Comment by GrantBirki** [comment]
This issue is related to https://github.com/github/branch-deploy/issues/73. There is more details in the issue linked and I will close in favor of said issue

**Comment by erickatwork** [comment]
> even just flat-out not waiting for CI to have finished run before we can go ahead with deploys.


@GrantBirki Hi, sorry for the ping on an old issue but I wanted to ask about OPs second question: is there a way to run `.deploy` and have deploy wait for CI checks to finish running (and succeed) before proceeding with the deploy?

**Comment by GrantBirki** [comment]
@erickatwork Hey no worries!

> is there a way to run `.deploy` and have deploy wait for CI checks to finish running (and succeed) before proceeding with the deploy?

This is actually the [default behavior](https://github.com/github/branch-deploy/blob/ea8c5e050da37060e9562f613d2ca9175451ff53/action.yml#L104-L107) of this Action. All instances of `.deploy` will be rejected unless all CI checks are passing on the pull request you are trying to deploy unless otherwise configured.

You can read even more about these features here: [checks docs](https://github.com/github/branch-deploy/blob/main/docs/checks.md)
