### ISSUE TITLE
Bug: does not observe required checks

### ISSUE THREAD

**Issue by hfaulds** [github/branch-deploy#73]
At the moment deploys are blocked on all status checks passing, even if they're not required.

This is because `statusCheckRollup.state` doesn't care about whether a check is required or not:

https://github.com/github/branch-deploy/blob/43afd75c657a06c55c953cc7af493d9cf565aa43/src/functions/prechecks.js#LL151

I don't know if there's an elegant way to check this 😢 (especially one that avoids paging through results). The best graphql I could come up with was this:

```
{
  repository(owner: "github", name: "branch-deploy") {
    pullRequest(number: 69) {
      reviewDecision
      commits(last: 1) {
        nodes {
          commit {
            checkSuites {
              totalCount
            }
            statusCheckRollup {
              state
              contexts(first: 100) {
                nodes {
                  ... on CheckRun {
                    isRequired(pullRequestNumber: 69)
                    conclusion
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by GrantBirki** [comment]
@hfaulds Some folks might actually want *all* checks rather than just the required ones. How would you feel about a new input parameter like:

```yaml
checks: all
```

> requires all checks to pass no matter what

and:

```yaml
checks: required
```

> only wait for required checks

---

Depending on which input param is used, that determines which graphql query we make to determine if we are 🟢 or not for the deploy.

Thoughts?

**Comment by hfaulds** [comment]
@GrantBirki introducing `checks: all` and `checks:required` makes a ton of sense to me 👍

**Comment by GrantBirki** [comment]
👋 Hey folks! I have good news. We had an excellent open source contribution to this project that has implemented the `checks` input option.

All details about this new input option can be found in the following release -> [`v9.1.0`](https://github.com/github/branch-deploy/releases/tag/v9.1.0).

Since it has been quite a while since this issue was first opened, I will go ahead and ping (@ mention) a few people that seemed interested in this feature.

@hfaulds @tiagonbotelho @metaory @kevinMSampson @paulEustice @redoz @bzurkowski

Cheers! 🎉
