### ISSUE TITLE
Can pass custom parameters?

### ISSUE THREAD

**Issue by CatsMiaow** [github/branch-deploy#91]
If managing multiple projects in one repository (like a monorepo), may need condition handling in deploy scripts to only deploy a specific project. (like [on.workflow_dispatch.inputs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs))

Is there any way currently possible?
For example `.deploy --project foobar` (Similar to `.lock --reason <text>`)

**Comment by GrantBirki** [comment]
There is a way to do this but its a little "hacky"!

You could have multiple workflows all calling the branch deploy Action. Rather than using the default `.deploy` as your trigger, you could use a different "trigger" for each project.

1. workflow file 1
  - contains the branch deploy Action
  - uses the config option `trigger: .deploy backend`
2. workflow file 2
  - contains the branch deploy Action
  - uses the config option `trigger: .deploy frontend`

etc...

---

This way you can have multiple workflow files, doing multiple things, with different triggers.

`.deploy backend` would run custom logic in a custom workflow to ship changes only to the components in your monorepo for your backend. Likewise, `.deploy frontend` would be similar but for frontend components.

Let me know if that helps!

**Comment by GrantBirki** [comment]
@CatsMiaow do you have any other questions or can this issue be closed? 😄

**Comment by CatsMiaow** [comment]
yes thanks for the reply
I can solve the problem with the method you suggested, so I'll close the issue.
Still, it would be nice if it could be solved in one workflow with custom parameters.

**Comment by penenkel** [comment]
For future reference: This seems to be available now: https://github.com/github/branch-deploy/blob/main/docs/parameters.md
