### ISSUE TITLE
Add an ignore-list for CI flows that should be ignored by commit status checks

### ISSUE THREAD

**Issue by necropolina** [github/branch-deploy#95]
Similar to https://github.com/github/branch-deploy/issues/93, but slightly different. I have some CI flows/actions that can take a bit of time and also don't affect deployability, so it'd be nice if I could have the status commit check pass even though those specific actions haven't completed.

**Comment by GrantBirki** [comment]
@necropolina Have you tried tweaking the `required_contexts` setting? This setting is designed for you to specify which CI checks are required for deployments. You could add all the checks that you want and leave out the ones that take a while to finish. It should be noted that I added this input variable a long time ago, added unit tests, but have never actually tested it in a live repository because I have not personally had the use for it yet. I added it in case others needed it but it isn't 100% supported due to the lack of integration testing that has been done in a live repo.

I would suggest giving that a go and report back how it works, thanks!

**Comment by GrantBirki** [comment]
Closing due to stale. There is a partial fix for this that was added here -> https://github.com/github/branch-deploy/pull/96
